### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by IsMoux** [Dudamchandana/Medical-Image-Fusion-for-Mri-Ct-Per-Spect#1]
hi can i have the paper where this architecture is base on

**Comment by Dudamchandana** [comment]
Hy Ismoux,
Here is the DOI of the paper, which i published. DOI: https://www.doi.org/10.56726/IRJMETS45033

**Comment by IsMoux** [comment]
thank you so much

Le ven. 15 mars 2024, 03:03, Chandana Dudam ***@***.***> a
écrit :
